# -*- coding: utf-8 -*-
"""LABOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDUXa3VzP_hnErCUjb3NDfuPnjpU0mkm

## imports
"""

!rm -rf data
!mkdir data 
!wget https://s3.eu-central-1.wasabisys.com/aicrowd-practice-challenges/public/labor/v0.1/test.csv
!wget https://s3.eu-central-1.wasabisys.com/aicrowd-practice-challenges/public/labor/v0.1/train.csv
!mv test.csv data/test.csv
!mv train.csv data/train.csv

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import f1_score,precision_score,recall_score,accuracy_score
import matplotlib.pyplot as plt

all_data_path = "data/train.csv" #path where data is stored

all_data = pd.read_csv(all_data_path) #load data in dataframe using pandas

all_data.head()

"""## Train"""

X_train, X_val= train_test_split(all_data, test_size=0.2)

X_train,y_train = X_train.iloc[:,:-1],X_train.iloc[:,-1]
X_val,y_val = X_val.iloc[:,:-1],X_val.iloc[:,-1]

model = CatBoostClassifier(iterations=500, learning_rate = 0.1, depth = 5, silent=True)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
f1 = f1_score(y_val,y_pred,average='macro')
print(f"LR= {lr} \tF1 score of the model is: {f1}")

final_test_path = "data/test.csv"
final_test = pd.read_csv(final_test_path)

submission = model.predict(final_test)
submission2=submission.round(0)

submission2=submission2.astype(int)
submission3 = pd.DataFrame(submission2)


submission3.to_csv('submission.csv',header=['class'],index=False)